### ISSUE TITLE
Pipeline actions are not logged

### ISSUE THREAD

**Issue by containscafeine** [fabric8-services/fabric8-jenkins-proxy#247]
I discovered in https://github.com/fabric8-services/fabric8-jenkins-idler/issues/223#issuecomment-385374429 that even though there are no logs in proxy, idler is getting requests to un-idle. The best guess is that proxy is not logging pipeline events, or pipelines UI is talking to idler directly, which is unlikely.

**Comment by kishansagathiya** [comment]
@containscafeine 

>  even though there are no logs in proxy, idler is getting requests to un-idle

That's because when you start a pipeline, instead of talking to proxy it talks to launcher-backend. Launcher-backend has a mini proxy inside it. There is an issue to move that code to proxy, but we have decided to do that once build.next is ready. Current proxy doesn't have the functionality to handle this request.
Pipeline UI is talking to launcher backend.

I think we can safely close this issue, wdyt?
