### ISSUE TITLE
Make sure that CORS doesn't occur on Prod or Prod-preview

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-jenkins-proxy#257]
From what I understand, UI was never talking to Jenkins-proxy using Ajax calls. With https://github.com/fabric8-ui/fabric8-ui/pull/2889 merged it would do so.

Make sure that when openshift.io talks to jenkins.openshift.io we don't see CORS error. 
How are we making this checks? Does it have to do just with how applications are deployed?

Will jenkins.openshift.io and openshift.io be considered to have the same origin(i.e., openshift.io) or different? Do we have to change anything on the proxy code for this?

Tagging @sbose78 @sthaha

**Comment by sthaha** [comment]
@kishansagathiya 
> Make sure that when openshift.io talks to jenkins.openshift.io we don't see CORS error.

To enable [CORS][cors] we have to set the appropriate `Access-Control-Allow-*` headers. See: [enabling cors][howto] which also links to https://github.com/rs/cors 

> How are we making this checks? 

We don't have to make these checks. IIUC, the browser does that. The server only needs to set the headers so that calling the api through XHR is allowed.

> Will jenkins.openshift.io and openshift.io be considered to have the same origin(i.e., openshift.io) or different? Do we have to change anything on the proxy code for this?

How about setting  `*.openshift.io`?  Perhaps this could be configurable so that we can handle the prod-preview as well. WDYT? 

[cors]: https://flaviocopes.com/cors/
[howto]: https://flaviocopes.com/golang-enable-cors/

**Comment by sbose78** [comment]
https://github.com/fabric8-services/fabric8-auth/search?q=CORS&type=Commits

**Comment by gastaldi** [comment]
Here is the simplest CORS filter I could find: https://github.com/fabric8-launcher/launcher-backend/blob/master/web/src/main/java/io/fabric8/launcher/web/providers/CorsFilter.java

**Comment by gastaldi** [comment]
@sthaha @kishansagathiya you also need to check if the method is an OPTIONS and return only the CORS headers, then the original request is sent.

[1] https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
